//Projects
// Get projects
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR";

export const GET_PLAYERS_SEARCH_BY_TEAM_REQUEST =
  "GET_PLAYERS_SEARCH_BY_TEAM_REQUEST";
export const GET_PLAYERS_SEARCH_BY_TEAM_SUCCESS =
  "GET_PLAYERS_SEARCH_BY_TEAM_SUCCESS";
export const GET_PLAYERS_SEARCH_BY_TEAM_FAILURE =
  "GET_PLAYERS_SEARCH_BY_TEAM_FAILURE";

export const GET_PLAYERS_SEARCH_BY_NAME_REQUEST =
  "GET_PLAYERS_SEARCH_BY_NAME_REQUEST";
export const GET_PLAYERS_SEARCH_BY_NAME_SUCCESS =
  "GET_PLAYERS_SEARCH_BY_NAME_SUCCESS";
export const GET_PLAYERS_SEARCH_BY_NAME_FAILURE =
  "GET_PLAYERS_SEARCH_BY_NAME_FAILURE";
